name: VSF Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  release-packages:
    name: "Release NPM Packages"
    uses: vuestorefront/integrations-github-workflows/.github/workflows/continuous-delivery.yml@main
    secrets: inherit
    with:
      enterprise: false
      # Set this to true if your package's dependencies are meant to be downloaded from VSF's private NPM repository,
      # and not on the public global NPM. False skips login and downloads deps from public NPM
      
      # If you set "true" here, you need to have repository secrets added in GitHub named exactly:
      # - NPM_USER
      # - NPM_PASS
      # - NPM_EMAIL 
      # Those are the username, password and e-mail of the Verdaccio user used to publish to the *PRIVATE* NPM repository

      # If you set "false" here, you need to have a repository secrets named exactly NPM_RELEASE_TOKEN
      # which you can get from Wojtek Sikora or Filip Rakowski, if you don't have it

